# Create a WSL script for SSH + SSHFS setup. User runs the script from inside WSL.
# Run from Windows PowerShell (e.g. in C:\Setup)
# Usage: .\SetupWslSshDeveloperEnv.ps1 -DeveloperId 06
#        .\SetupWslSshDeveloperEnv.ps1 -DeveloperId 01

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$DeveloperId,

    [Parameter(Mandatory = $false)]
    [switch]$Docker,

    [Parameter(Mandatory = $false)]
    [string]$WslDistro = "Ubuntu"
)

$ErrorActionPreference = "Stop"
$WinUser = $env:USERNAME
$WinSsh = "C:\Users\$WinUser\.ssh"
$DevHost = "dev$DeveloperId.aifabrix"
$DevUser = "dev$DeveloperId"
$WorkspaceDir = "dev$DeveloperId-workspace"

# --- Checks ---
if (-not (Test-Path $WinSsh)) { throw "Windows .ssh not found: $WinSsh" }
foreach ($f in @("id_ed25519", "id_ed25519.pub", "config")) {
    if (-not (Test-Path "$WinSsh\$f")) { throw "Missing: $WinSsh\$f" }
}

$ScriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Get-Location }
$OutSh = Join-Path $ScriptDir "setup-wsl-ssh-dev$DeveloperId.sh"

$shContent = @"
#!/bin/sh
# Run this script inside WSL. Generated by SetupWslSshDeveloperEnv.ps1
# When Docker is installed, Windows C: is at /mnt/host/c.

WIN_USER="$WinUser"
USE_DOCKER_PATH="$($Docker.IsPresent)"

# With Docker: C: is at /mnt/host/c. Without: try /mnt/host/c then /mnt/c.
if [ "`$USE_DOCKER_PATH" = "True" ]; then
  WIN_SSH="/mnt/host/c/Users/`$WIN_USER/.ssh"
  if [ ! -d "`$WIN_SSH" ]; then
    echo "ERROR: Windows .ssh not found at `$WIN_SSH (Docker path /mnt/host/c)" >&2
    exit 1
  fi
else
  if [ -d "/mnt/host/c/Users/`$WIN_USER/.ssh" ]; then
    WIN_SSH="/mnt/host/c/Users/`$WIN_USER/.ssh"
  elif [ -d "/mnt/c/Users/`$WIN_USER/.ssh" ]; then
    WIN_SSH="/mnt/c/Users/`$WIN_USER/.ssh"
  else
    echo "ERROR: Windows .ssh not found. Tried /mnt/host/c and /mnt/c" >&2
    exit 1
  fi
fi

for f in id_ed25519 id_ed25519.pub config; do
  if [ ! -f "`$WIN_SSH/`$f" ]; then
    echo "ERROR: Missing `$WIN_SSH/`$f" >&2
    exit 1
  fi
done

echo "Using Windows SSH from: `$WIN_SSH"
mkdir -p ~/.ssh
chmod 700 ~/.ssh
cp "`$WIN_SSH/id_ed25519"     ~/.ssh/
cp "`$WIN_SSH/id_ed25519.pub" ~/.ssh/
chmod 600 ~/.ssh/id_ed25519
cp "`$WIN_SSH/config" ~/.ssh/config
chmod 600 ~/.ssh/config

if ! grep -q 'Host ${DevHost}' ~/.ssh/config; then
  echo '' >> ~/.ssh/config
  echo 'Host ${DevHost}' >> ~/.ssh/config
  echo '  HostName ${DevHost}' >> ~/.ssh/config
  echo '  User ${DevUser}' >> ~/.ssh/config
  echo '  IdentityFile ~/.ssh/id_ed25519' >> ~/.ssh/config
  echo '  PreferredAuthentications publickey' >> ~/.ssh/config
fi

# Install sshfs if we have a package manager
SSHFS_OK=0
if command -v sshfs >/dev/null 2>&1; then
  SSHFS_OK=1
elif command -v sudo >/dev/null 2>&1 && command -v apt-get >/dev/null 2>&1; then
  if sudo apt-get update -qq && sudo apt-get install -y sshfs; then SSHFS_OK=1; fi
elif command -v apk >/dev/null 2>&1 && [ "`$(id -u)" = "0" ]; then
  if apk add --no-cache openssh-client sshfs 2>/dev/null; then SSHFS_OK=1; fi
fi

mkdir -p ~/${WorkspaceDir}
ssh-keyscan -H ${DevHost} >> ~/.ssh/known_hosts 2>/dev/null || true
echo ""
echo "SSH keys and config ready."

if [ "`$SSHFS_OK" = "1" ]; then
  echo "Mount ${WorkspaceDir} with:"
  echo "  sshfs ${DevHost}:/home/${DevUser} ~/${WorkspaceDir} -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3"
  echo ""
  read -p "Mount now? (y/N): " mount_choice
  case "`$mount_choice" in
    [yY])
      sshfs ${DevHost}:/home/${DevUser} ~/${WorkspaceDir} -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3
      echo "Mounted. Access at ~/${WorkspaceDir} (use from WSL only; Windows Explorer cannot open sshfs mounts)"
      ;;
    *)
      echo "Skipped. Run the sshfs command above when ready."
      ;;
  esac
else
  echo "This environment has no sudo/apt/sshfs. Run from Ubuntu WSL:"
  echo "  wsl -d Ubuntu"
  echo "  cd /mnt/c/Setup   # or  cd /mnt/host/c/Setup"
  echo "  ./setup-wsl-ssh-dev$DeveloperId.sh"
  echo ""
  echo "Or install sshfs and run:"
  echo "  sshfs ${DevHost}:/home/${DevUser} ~/${WorkspaceDir} -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3"
fi
"@

# Write with LF only (Unix line endings) so WSL runs it correctly
$shContent = $shContent -replace "`r`n", "`n" -replace "`r", ""
[System.IO.File]::WriteAllText($OutSh, $shContent, [System.Text.UTF8Encoding]::new($false))

# Copy script to WSL home (e.g. C:\Setup\file.sh -> /mnt/c/Setup/file.sh)
$drive = (Get-Item $OutSh).PSDrive.Name.ToLower()
$relPath = $OutSh.Substring(2).TrimStart('\').Replace('\', '/')
$wslPath = "/mnt/$drive/$relPath"
$shName = "setup-wsl-ssh-dev$DeveloperId.sh"
wsl -d $WslDistro sh -c "cp `"$wslPath`" ~/$shName && chmod +x ~/$shName"
if ($LASTEXITCODE -ne 0) {
    Write-Host "Could not copy script to WSL home (is $WslDistro running?). You can copy manually." -ForegroundColor Yellow
} else {
    Write-Host "Script copied to WSL home (~/$shName)." -ForegroundColor Green
}

Write-Host ""
Write-Host "Next: log into WSL and run:" -ForegroundColor Cyan
Write-Host "  wsl -d $WslDistro" -ForegroundColor Gray
Write-Host "  ~/$shName" -ForegroundColor Gray
Write-Host "  # or:  cd ~ && ./$shName" -ForegroundColor Gray
Write-Host ""
Write-Host "You can answer sudo and 'Mount now? (y/N)' in WSL." -ForegroundColor Yellow
Write-Host "Note: The workspace folder is an sshfs mount. Use it from WSL only (terminal or Cursor/VS Code WSL); Windows Explorer cannot open it." -ForegroundColor Gray
